apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-system-ingress
  namespace: kube-system
spec:
  ingressClassName: cilium
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hubble-ui
            port:
              number: 80
        path: /hubble
        pathType: Prefix